### PR TITLE
one control regression, use predict()

### PR DESCRIPTION
**Pull request by jennybc**
I added a section at the bottom with a simpler approach. I don't think you even need `group_by()` in this case. I think my single, control regression is what @gavinsimpson was also getting at. I like this parametrization better, for interpretability.

### CODE REVIEW

**Comment by jennybc** [comment]
Oh, I also switched output to `github_document`. This way you can render or knit and get nice `.md` that is a pretty, viewable report on GitHub. Html is not viewable on GitHub.

**Comment by gavinsimpson** [comment]
Yup that's a clearer/better parametrisation than the standard factor-continuous interaction I used in #2; even though the models are the same (fitted values), it's clearer here.

**Comment by jennybc** [comment]
I'm not entirely clear about the meaning of rep vs order. The original report uses one to plot (rep) and the other for the regression (order), so I copied that. But I suspect that should be given a hard look and possibly made consistent?

**Comment by duffymeg** [comment]
Thank you for all this! The rep. vs. order thing was a mistake in the plot -- that should have been order. Thank you for catching that!

I really like your approach to the regressions and think it should work well even when I've added in the additional data. Now to go test that hypothesis! 

Thanks again!

**Comment by jennybc** [comment]
My pleasure!

**Comment by duffymeg** [comment]
If it's useful to you as a class example, go ahead and use it!

**Pull request merged**
